### ISSUE TITLE
Silent options aren't silent

### ISSUE THREAD

**Issue by teknowledgist** [RealityRipple/SecondFactor#2]
Hi.  Nice software!  Two questions:

1. Is there any way to prevent SecondFactor from auto-opening on install?  
2. The "QuietUninstallString" in the registry for SecondFactor:

    "C:\Program Files\RealityRipple Software\SecondFactor\unins000.exe" /SILENT

isn't actually silent.  It pops up two dialogs related to saving Authentication Profiles.  Can those be avoided?

Thanks!

**Comment by RealityRipple** [comment]
Normally, I'd say no to the first task as I use the silent method for the update process in my projects that auto-update, but SecondFactor does not, so run on startup can have the `skipifsilent` flag.
**However**, it sill will run with the `-reg` parameter to register the `otpauth://` protocol in your registry.

The uninstall is easy enough to implement as well. The profiles and app directory will be deleted on silent uninstall, with no prompt.

---

The new installer is now available - note that it has a File version of `1.4.4.2` which is different from the Product version `1.4.4`, to denote the change in the installer, with no change to the application itself.
